- name: This playbook will install, configure and deploy webpage into nginx web server
  hosts: all
  vars_files:
     - myvars.yml
  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"
    - include: common-tasks.yml
    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"
    - include: deploy-webpage.yml
    - include: restart-nginx.yml


