- name: This playbook demonstrates provisioning containers
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Install Python Package Installer (PIP)
      shell: yum install -y python-pip

    - name: Install docker-py module
      shell: pip install docker-py

    - name: Create CentOS containers
      docker_container:
        docker_host: "tcp://localhost:4243"
        image: "qualcomm/ansible-centos"
        name: "centos{{item}}"
        hostname: "centos{{item}}"
        published_ports:
          - "2{{item}}:22"
          - "8{{item}}:80"
      with_sequence: start=1 end=10 format=%03d

    - name: Create Ubuntu containers
      docker_container:
        docker_host: "tcp://localhost:4243"
        image: "qualcomm/ansible-ubuntu"
        name: "ubuntu{{item}}"
        hostname: "ubuntu{{item}}"
        published_ports:
          - "3{{item}}:22"
          - "9{{item}}:80"
      with_sequence: start=1 end=10 format=%03d

