- name: Install Extra Packages for Enterprise Linux(EPEL) in CentOS 
  yum: name=epel-release state=latest disable_gpg_check=yes 

- name: Install nginx web server in CentOS 
  yum: name=nginx state=latest 
