- name: This playbook will install JDK and Maven in containers
  hosts: all
  become: yes
  tasks:
    - name: Copy Maven archive file
      copy: src=apache-maven-3.6.2-bin.tar.gz dest=/root/apache-maven-3.6.2-bin.tar.gz

    - name: Extract maven 
      shell: tar xvfz /root/apache-maven-3.6.2-bin.tar.gz
